# Generated by Django 4.0 on 2022-08-22 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WordsDRF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameCategory', models.CharField(choices=[('transport', 'Transport'), ('home', 'Home'), ('street', 'Street')], max_length=9, verbose_name='WordClass')),
            ],
        ),
        migrations.RemoveField(
            model_name='words',
            name='wordClass',
        ),
        migrations.AddField(
            model_name='words',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WordsDRF.category'),
        ),
    ]
