# Generated by Django 4.0 on 2022-08-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordsDRF', '0002_category_remove_words_wordclass_words_catagory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(choices=[('food', 'Food'), ('home', 'Home'), ('street', 'Street')], max_length=9, verbose_name='WordClass'),
        ),
    ]
