# Generated by Django 4.0 on 2022-08-22 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WordsDRF', '0003_alter_category_namecategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='nameCategory',
            field=models.CharField(choices=[('food', 'Food'), ('home', 'Home'), ('street', 'Street')], db_index=True, max_length=9, verbose_name='WordClass'),
        ),
    ]
