# Generated by Django 4.0 on 2022-09-27 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SentencesDRF', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='catagory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='catagory', to='SentencesDRF.category'),
        ),
    ]
